# Generated by Django 4.2.2 on 2023-12-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_sate_deliveryaddress_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(upload_to="userprofile"),
        ),
    ]
